---
default:
  rails:
    session_name: 'smeg-head-session'
    secret: 'a-randomly-generated-session-key-that-you-need-to-know-to-update'
  devise:
    pepper: "a-long-random-string-goes-here-for-devise-to-handle-authentication"
  smeg_head:
    host: 'localhost'
    user: 'git'
  commands:
    git_shell: '/usr/local/bin/git-shell'