#!/usr/bin/env ruby
require 'drb/drb'
require 'drb/unix'

def env(name)
  ENV['SH_' + name.to_s.upcase]
end

def die!(message)
  STDERR.puts message
  exit 1
end

drb_uri = env(:drb_server)
die! "No drb server found for communication" if drb_uri.to_s.empty?

DRb.start_service # Required for callbacks etc.
manager = DRbObject.new_with_uri(drb_uri)

refs = []

STDIN.each_line do |line|
  old_ref, new_ref, full_ref = line.strip.split(" ", 3)
  refs << [old_ref, new_ref, full_ref]
end

manager.notify_refs! refs

exit 0